# Intro to Numpy

In [1]:
import numpy as np

Define a $(3,2)$ numpy array called arr which is populated by zeroes.

In [2]:
arr = np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Change the first row of your array to all ones.

In [3]:
arr[0] = 1
arr

array([[1., 1.],
       [0., 0.],
       [0., 0.]])

Change the rest of your array (should be four numbers) to the first 4 square numbers, ascending row-wise.

In [4]:
sq_numbers = np.square(np.arange(1,5)) # Use numpy functions to get first 4 square numbers
sq_numbers = sq_numbers.reshape(2,2) # Rehshape array of square numbers to the correct shape to fit in array
arr[1:] = sq_numbers
arr

array([[ 1.,  1.],
       [ 1.,  4.],
       [ 9., 16.]])

Sum your array so that the result is a vector containing the sum of each column.

In [5]:
np.sum(arr,axis=0)

array([11., 21.])

Create a new nd-array of size $(2,5)$ which is populated by ascending multiples of 2 row-wise, i.e. 2,4,6,8 etc.

In [6]:
multiples_of_two = np.arange(2,21,2)
multiples_of_two.reshape((2,5))

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

Extract all positive numbers from the following array

In [7]:
random_array = np.random.randn(1,5)
random_array[random_array > 0]

array([0.14836347, 0.06990901, 0.40899944, 1.05776158])

Change those positive numbers you just extracted to 0 in the inital array

In [8]:
random_array[random_array > 0] = 0
random_array

array([[ 0.        ,  0.        ,  0.        , -0.71583016,  0.        ]])

Grab all the numbers which lie between -2 and 2 in the array:

In [9]:
arr = 5*np.random.randn(1,10)
arr

array([[ -1.38701141,   4.74040486,  -6.19203041,   3.87016232,
         -4.12829857,  -1.52505722, -11.40279713,   5.52319752,
         -3.37120647,  -2.97509517]])

In [10]:
arr[np.logical_and(arr > -2, arr < 2)] 
# Careful - you can't use python's AND because it only works between two singular booleans!

array([-1.38701141, -1.52505722])